name: Artifact Upload and Download

on:
  push:
    branches:
      - main

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create artifact
        run: |
          echo "apple" > apple.txt
          echo "banana" > banana.txt
          echo "cherry" > cherry.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fruits
          path: |
            apple.txt
            banana.txt
            cherry.txt
          retention-days: 1

  download-artifact:
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: fruits

      - name: List files
        run: |
          ls -la
          cat apple.txt
          cat banana.txt
          cat cherry.txt
