name: call workflow
run-name: call-workflow
on: workflow_dispatch
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    outputs:
      message: "hello"
    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: echo hello
        run: |
          echo "hello world"

  call-workflow:
    needs: [echo-hello]
    uses: ./.github/workflows/called-by-other.yml
    with:
      animal: "cat"

  output-result:
    needs: [call-workflow]
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: output result
        run: |
          # echo "result: ${{ needs.call-workflow.outputs.message }}"
