name: local-env
on: workflow_dispatch
jobs:
  job001:
    runs-on: ubuntu-latest
    steps:
      - name: set env
        run: |
          hello="hello world"
          echo $hello
      - name: read env
        run: |
          echo $hello
